### ISSUE TITLE
gitlabUrl could be retrieved from package.json

### ISSUE THREAD

**Issue by oupala** [semantic-release/gitlab#105]
The `gitlabUrl` value is currently is retrieved from an environment variable (or has a default value) (see [documentation](https://github.com/semantic-release/gitlab#options)):

> `GL_URL` or `GITLAB_URL` environment variable or `https://gitlab.com`

In fact the information is already available in the `package.json` file (if any) in the `repository.url` field. Could it be a source of information sourced, in order to avoid repeating the same information?

This usecase is already implemented in the [npm plugin](https://github.com/semantic-release/npm#options) where the `private` field is checked to see if the npm package should be published to npmjs or not.

**Comment by pvdlg** [comment]
The `repositoryUrl` and the `gitlabUrl` are two different things. `repositoryUrl` is the URL of the Git repo,  `gitlabUrl`  is the URL of the GitLab API. Those might overlap but not necessarily.

I don't think there is a way to determine that with certainty. If you know one let us know.

**Comment by amclin** [comment]
I'm running into a situation where `gitlabUrl` is not being used from package.json:
```
      [
        "@semantic-release/gitlab",
        {
          "gitlabUrl": "https://private-registry.example.com"
        }
      ]
```

When I look at errors in my logs, I can see that the `repository.url` is being used instead, even though I provided gitlabUrl specifically for this scenario:
```
[7:22:12 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/gitlab"
[7:22:12 PM] [semantic-release] › ✔  Run automated release from branch master
[7:22:12 PM] [semantic-release] › ✖  The command "undefined" failed with the error message fatal: unable to access 'https://gitlab-ci-token:@<domain extracted from repository.url in package.json>/MY-GROUP/my-project.git/': gnutls_handshake() failed: An unexpected TLS packet was received..
[7:22:12 PM] [semantic-release] › ✖  EGITNOPERMISSION Cannot push to the Git repository.
semantic-release cannot push the version tag to the branch master on the remote Git repository with URL https://gitlab-ci-token:@<domain extracted from repository.url in package.json>/MY-GROUP/my-project.git.
```
It does work if I provide `GITLAB_URL` as an environment variable. So why would the environment variable work, but the expected property in package.json not?

**Comment by oupala** [comment]
> Those might overlap but not necessarily.

It should overlap most of the time though. It could then be deducted from `repositoryUrl` by default, and allow overriding by the user when  it does not overlap.

@amclin You're issue is a bit different. I think you should open a specific issue for your problem.

**Comment by pvdlg** [comment]
Parsing Git URL is a lot more difficult than what it seems and we had a lot of issues in the past with that.
That's because there is multiple ways to define a Git URL: http, http+git, git (as in `git@host:owner/repo`) or ssh.

So that leave us in several situations were we can't determine the API URL based on the repo URL. For example with a `git` or `ssh` we cannot get the port.

We prefer to force users to define the API URL to avoid ambiguity as we don't want a situation that work only sometimes. It would be confusing and unnecessarily complex to have to explain to users that the `gitlabUrl` is required unless the API URL `repositoryUrl` is defined as `https` and uses the same port.

Finally most users use the public GitLab instance and don't have to configure `gitlabUrl`. Only the (relatively) few users who have a private would benefit from the feature you are requesting. So having more confusing rules and documentation in exchange of sparing one config line for few users is not a worthwhile tradeoff.

**Comment by pvdlg** [comment]
@amclin as I explained in the previous message `repository.url` and `gitlabUrl` are two different things.
`repositoryUrl` is used for Git calls, `gitlabUrl` is used for API calls.
The error you have is related to `repository.url` and it happens because semantic-release doesn't have the permission to run `git push`.

**Comment by oupala** [comment]
I agree it would be touchy to parse the `repositoryUrl` in order to deduct `gitlabUrl` as there is many edge cases.

However, there could be some alternative to defining a specific `GITLAB_URL` variable:

- `CI_API_V4_URL` is directly the api url, replacing `GITLAB_URL` **and** `GITLAB_PREFIX`
- `CI_SERVER_HOST` is the GitLab hostname, replacing `GITLAB_URL`

```bash
$ echo ${GITLAB_URL}
https://gitlab.local/

$ echo ${CI_API_V4_URL}
https://gitlab.local/api/v4

$ echo ${CI_SERVER_HOST}
gitlab.local
```

It is a shame to be oblige to declare the GitLab url into a GitLab CI pipeline. GitLab knows about its own url.
