### ISSUE TITLE
verification failed when user added via group sharing

### ISSUE THREAD

**Issue by kurpipio** [semantic-release/gitlab#153]
currently verification relies on `api/v4/projects/${PROJECT_ID}` and fails when project is shared with group and user is member of that group, because in such situation API says project_level and group_level are null. Thus we end up in the situation when user has all required permissions, but verification fails.

It's already reported to GitLab https://gitlab.com/gitlab-org/gitlab/-/issues/223832, but still I believe it's a bug that should be fixed here - verification says "no permissions", while user has all required permissions.

**Comment by nfriend** [comment]
@kurpipio Thanks for this, this looks like the same as https://github.com/semantic-release/gitlab/issues/165. (Well, technically _it's_ the same as this one, since this one was opened first 🙂).

See [my comment on that issue](https://github.com/semantic-release/gitlab/issues/165#issuecomment-738303604) for a possible workaround using a [project access token](https://docs.gitlab.com/ee/user/project/settings/project_access_tokens.html) - would this work in your situation?

**Comment by fgreinacher** [comment]
Closing this as the #165 is essentially the same.
