### ISSUE TITLE
Create GitLab release only on tags pipeline

### ISSUE THREAD

**Issue by jeff-cook** [semantic-release/gitlab#159]
I'm looking for a way to create the GitLab release (links to assets and release notes text) only when the pipeline runs on the git tag. 

My use case

- The builds in the pipeline use `$CI_BUILD_TAG` to build the artifacts
- The artifacts are built with the version known and used in the build
- These are the artifacts that are linked in the GitLab release

The GitLab release API doesn't support updating the links after it is created. 

I'm replacing a workflow that use https://github.com/c4urself/bump2version and https://gitlab.com/alelec/gitlab-release to manually trigger creation of versioned tag, and automatically create the GitLab release for the tag.

**Comment by nfriend** [comment]
> I'm looking for a way to create the GitLab release (links to assets and release notes text) only when the pipeline runs on the git tag.

@jeff-cook Have you considered only running the job that executes `semantic-release` on tag pipelines? Something like this:

```yml
publish:
  stage: release
  script:
    - npm run semantic-release
  rules:
    - if: $CI_COMMIT_TAG
```

You could also restrict this further by only running the job on tags that match a certain pattern:

```yml
  rules:
    - if: $CI_COMMIT_TAG && $CI_COMMIT_REF_NAME =~ /^v\d+\.\d+\.\d+.*$/
```

> The GitLab release API doesn't support updating the links after it is created.

There is an "update release asset links" API: https://docs.gitlab.com/ee/api/releases/links.html#update-a-link. Does this do what you need?

**Comment by jeff-cook** [comment]
My current workflow is to run `semantic-release` on the default branch, to create a git tag for a release. 
Then, run a different tool to create the GitLab release with artifacts created in the tag's pipeline.

Is there a way to use `semantic-release` to perform this within the same project/config file?
The job would need to be run twice. 
Once on default and once on the tag.

**Comment by r4j4h** [comment]
Yeah I think you would just define two different configs, one for the branch pipeline and another for the tag pipeline, using `semantic-release --extends <config>` to select between them.

The branch pipeline would be customized to only use plugins like commit analyzer, changelog, git (so it tags), etc, but not gitlab.

The tag pipeline would be customized to only use plugins like gitlab. I think you will need to also customize the parts from using `nextRelease` to use `lastRelease` since on the tag it will think that is the last release at that point, but I haven't tried this so am not sure yet.

They could share a base config that they customize further so everything common does not have to be repeated, and which can highlight what does differ.

I have also been wondering what is more preferable, using semantic-release to and also generate/publish artifacts, or whether to just use semantic-release to tag and use tag pipelines to generate/publish the artifacts.

Using semantic-release for all of it has the gain of semantic-release plugins being able to update files (especially with `@google/semantic-release-replace-plugin`)
But since in this case you would be on a tag, you could still update files dynamically in the tag pipeline before publishing and it would be all the same in most cases.

I think if you don't already have it, the plugin is probably most convenient.
But if you already have complex, functional tag pipeline, might as well utilize it.

If you really want to keep the focus on semantic-release in the case you already have tag pipelines, there's more than one additional option to marrying them:
- You could transpose the tag pipeline's script into a javascript function and use it as a custom plugin, then you could have what you are doing done by semantic-release. But at the end of the day it's largely a refactor.
- You could transpose the tag pipeline's script into a script file and have the pipeline trigger it for now. Then when you incorporate semantic-release you can drop the job and use the `@semantic-release/exec` plugin to run the script at the right times.
-

**Comment by fgreinacher** [comment]
I think the replies above show some quite good options that are available right now. Feel free to reopen or create a new issue for things that are missing.
