### ISSUE TITLE
Plugin fails with ERR_INVALID_URL since NO_PROXY uses a ULR parser

### ISSUE THREAD

**Issue by jgoelten** [semantic-release/gitlab#360]
**Report**
Since version v9.1.0 of the gitlab plugin for semantic-release the plugin fails with an error. The introduction of NO_PROXY support in v9.1.0 contains a new URL parser (see https://github.com/semantic-release/gitlab/commit/3051799160efc127585d30a4ef776ccf34185fee#diff-3c41bd6e7d07732417abb44146ae10fa613e5d61d5df96d088e44cb8d5dc557fR66)  which now fails for urls without a protocol defined. This used to work so far.

**Steps to reproduce**
1. Install version v9.1.0 of gitlab semantic release plugin
2. Set envrionment variable `GITLAB_URL` to `gitlab.my-company.ch` (without https Prefix)
3. Start the semantic-release versioning job
4. The job fails with the error message `An error occurred while running semantic-release: TypeError [ERR_INVALID_URL]: Invalid URL`

**Affected Version**
v9.1.0 (https://github.com/semantic-release/gitlab/releases/tag/v9.1.0)

**Reason**
NO_PROXY feature now uses a url parser (new URL(...)) which fails for GITLAB_URL variables that contain a gitlab url without protocol prefixes. Can be easily reproduced with F12 dev-tools.

**Workaround**
Removing `GITLAB_URL` variable as part of our gitlab-ci.yaml configuration solves this issue since the gitlab plugin falls back to the gitlab's runner url provided through default variables.

**Comment by fgreinacher** [comment]
@Babbafett Could you have a look?

**Comment by Babbafett** [comment]
> @Babbafett Could you have a look?

The thing is that the used hpagent package requires to know to which type of protocol the connection is establish means http or https:
<img width="346" alt="image" src="https://user-images.githubusercontent.com/5669913/162964298-1d7db4ea-de55-408a-b4df-ee456d94aa87.png">

Because depending on that either the HttpProxyAgent or HttpsProxyAgent object needs to be selected
We could either say that without providing a protocol scheme in the gitlabUrl var https is selected or we don't allow proxying when not protocol scheme is provided (that was the behaviour after the initial proxy implementation).

For now I created a [PR](https://github.com/semantic-release/gitlab/pull/362) to check the scheme inside of the shouldProxy function and it is not allowed to proxy without providing the protocol scheme.
