### ISSUE TITLE
Failing to publish assets with url without specifying `path`

### ISSUE THREAD

**Issue by Krewedk0** [semantic-release/gitlab#382]
Release 9.3.0 (#322) introduced a feature to publish assets with direct links when `url` field specified in asset.
But `path` field is still required for this to work, otherwise release fails with 

`The assets option (https://github.com/semantic-release/gitlab/blob/master/README.md#assets) must be an Array of Strings or Objects with a path property.`

This check wasn't changed here https://github.com/semantic-release/gitlab/blob/master/lib/verify.js#L18
as `path` should be optional in this case, according to the readme.

**Comment by fgreinacher** [comment]
@awcjack Can you have a look?

**Comment by awcjack** [comment]
Didn't realize it when rebase  
I will create pull request later

**Comment by fgreinacher** [comment]
:tada: This issue is resolved in version 9.3.2 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@semantic-release/gitlab/v/9.3.2)
- [GitHub release](https://github.com/semantic-release/gitlab/releases/tag/v9.3.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:
