### ISSUE TITLE
Release asset URLs are incorrect

### ISSUE THREAD

**Issue by fgreinacher** [semantic-release/gitlab#579]
> This fix caused the downloaded files to be unavailable. 
> The assets files url now contains the Project ID instead of the project name, which made the files inaccessible. Manually fixing the link means that the file is available for download. 
> Perhaps this is our problem with self-hosted GitLab. We decided to roll back to semantic-release/gitlab ver 12.0.3
> 

_Originally posted by @JedaiRussia in https://github.com/semantic-release/gitlab/issues/576#issuecomment-1670059770_

**Comment by fgreinacher** [comment]
Thanks for pointing that out @JedaiRussia. I'll prepare a fix for this.

**Comment by roberthenzel** [comment]
I was just writing this issue. The bug is connected to this [commit ](https://github.com/semantic-release/gitlab/commit/335015222ef718ff4e77cb0f598428d3dce43313)
It attach the asset under gitlab.com/:id/ which is an incorrect URL.
![image](https://github.com/semantic-release/gitlab/assets/15844093/3c6a9923-9efb-4396-86c2-5d46752cbfd4)

```
{
        "name": "Swagger for DEV environment",
        "url": "https://gitlab.com/28502938/uploads/9f52bfe3c542dc9cd97f460c2b89587f/API_DEV.json"
 }
```
In previous version it was like that:
`{
        "name": "Swagger for DEV environment",
        "url": "https://gitlab.com/:organisation/:project/uploads/9f52bfe3c542dc9cd97f460c2b89587f/API_DEV.json"
 }`
